name: pony
description: Pony

inputs:
    - key: OS_REGION_NAME
      description: The region where the stack will be installed
      type: openstackRegion
      required: true
    - key: OS_KEYPAIR_NAME
      description: The keypair name used to spawn the instances
      type: openstackKeypairName
      required: false

constraints:
    - name: instances
      values:
      - flavor: b2-7
        minimum: 3

install:
    - echo pony > pony
    - cat pony
    - echo pony >> pony
    - mv pony ponies
    - cat ponies
    - echo "a wild pony appears"

commands:
    - name: init
      command: cat ponies

    - name: deploy
      command: echo pony >> ponies

    - name: helper
      command: echo PONIES EVERYWHERE
